### ISSUE TITLE
Async operations throws tons of errors

### ISSUE THREAD

**Issue by Maxetto** [hugo4715/KnockbackPlusPlus#1] opened 2017-06-10 11:30 UTC
Having those errors in every server of mine, happens to be yours plugin or your implementation of TinyProtocol.
Using PaperSpigot 1.8.8
```
[11:11:03] [Netty Epoll Server IO #2/ERROR]: stopTiming called async for world - chunkLoad - Entities
[11:11:03] [Netty Epoll Server IO #2/WARN]: java.lang.Throwable
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at co.aikar.timings.TimingHandler.stopTiming(TimingHandler.java:114)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkRegionLoader.loadEntities(ChunkRegionLoader.java:424)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:46)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:135)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:117)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:145)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:91)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getBlockAt(CraftWorld.java:592)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at org.bukkit.Location.getBlock(Location.java:87)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at tk.hugo4715.anticheat.player.ACPlayer.hasCeiling(ACPlayer.java:23)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at tk.hugo4715.anticheat.check.KbChecker.onPacketEvent(KbChecker.java:47)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.GeneratedMethodAccessor109.invoke(Unknown Source)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at tk.hugo4715.tinyprotocol.handler.tinyprotocol.TinyProtocolAccessor$1.onPacketOutAsync(TinyProtocolAccessor.java:32)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at tk.hugo4715.tinyprotocol.handler.tinyprotocol.TinyProtocol$PacketInterceptor.write(TinyProtocol.java:509)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:651)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:112)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:658)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:716)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:706)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:741)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:895)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:240)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at net.minecraft.server.v1_8_R3.NetworkManager$4.run(NetworkManager.java:198)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$5$3.run(ChannelInjector.java:340)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:268)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
[11:11:03] [Netty Epoll Server IO #2/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

Please fix it ASAP.

**Comment by Maxetto** [comment] 2017-06-10 11:32
Also, could you please remove such debugging message spam?
`reached: 1.9645524914033814 needed: 0.9309677419354838  %:-111.0226168867111 bool: false`

**Comment by hugo4715** [comment] 2017-06-10 17:49
The debug log was removed in the latest update. 
I think the problem is PaperSpigot itself (i never tested that)

**Comment by Maxetto** [comment] 2017-06-10 18:50
Yeah, it is. It goes in conflict with the V2 Timings from Aikar. You can't call Async bukkit internals with that.

**Comment by hugo4715** [comment] 2017-06-10 19:45
Ok, in the future i may sync the whole scanning procress to fix that.

**Comment by hugo4715** [comment] 2017-06-15 19:55
This bug should be fixed in the latest commit. You are free to reopen the issue if there is still an error
Thanks

**Closed as completed** 2017-06-15 19:55 UTC
Labels: bug, Working on it
